package com.moneyflowbackend.quickentry.dto;

public enum VoiceIntentType {
    TRANSACTION_EXPENSE,
    TRANSACTION_INCOME,
    TRANSACTION_TRANSFER,
    WALLET_BALANCE_SNAPSHOT,
    DEBT_PAYMENT,
    DEBT_CREATE,
    SAVINGS_GOAL_CONTRIBUTION,
    SINKING_FUND_CONTRIBUTION,
    EMERGENCY_FUND_CONTRIBUTION,
    RECURRING_OBLIGATION_PAYMENT,
    UNKNOWN_UNSUPPORTED
}
