package com.moneyflowbackend.quickentry.dto;

public enum VoiceIntentType {
    TRANSACTION_EXPENSE,
    TRANSACTION_INCOME,
    TRANSACTION_TRANSFER,
    WALLET_BALANCE_SNAPSHOT,
    DAILY_CLOSING,
    DEBT_PAYMENT,
    DEBT_CREATE,
    DEBT_CREATE_RECEIVABLE,
    DEBT_CREATE_PAYABLE,
    LOAN_DISBURSEMENT,
    LOAN_COLLECTION,
    BORROWING_RECEIPT,
    PAYABLE_REPAYMENT,
    INTEREST_EXPENSE,
    INTEREST_INCOME,
    SAVINGS_GOAL_CONTRIBUTION,
    SINKING_FUND_CONTRIBUTION,
    EMERGENCY_FUND_CONTRIBUTION,
    RECURRING_OBLIGATION_PAYMENT,
    STAT_QUERY,
    ANALYTICS_QUERY,
    UNKNOWN_UNSUPPORTED
}
