package com.moneyflowbackend.insight.dto;

public enum ActionItemType {
    TRANSACTION_MISSING_CATEGORY,
    TRANSACTION_MISSING_WALLET,
    INCOME_WITHOUT_WALLET,
    VOICE_DRAFT_PENDING,
    RECEIPT_DRAFT_PENDING,
    OCR_REVIEW_REQUIRED,
    PLANNED_OBLIGATION_MISSING_DATE,
    DEBT_MISSING_DUE_DATE,
    RESERVE_DATA_MISSING,
    UPCOMING_OBLIGATION_DATA_MISSING,
    NEGATIVE_ACTUALLY_SPENDABLE,
    LOW_ACTUALLY_SPENDABLE,
    HISTORICAL_DATA_EXCLUDED_FROM_WALLET,
    DATA_QUALITY_PARTIAL
}
