package com.moneyflowbackend.insight.dto;

public enum SpendableWarningCode {
    RESERVE_DATA_UNAVAILABLE,
    UPCOMING_OBLIGATION_DATA_UNAVAILABLE,
    OBLIGATION_STATUS_UNAVAILABLE,
    MIXED_CURRENCY_UNSUPPORTED,
    WALLET_BALANCE_SOURCE_UNCLEAR,
    NEGATIVE_SPENDABLE,
    PARTIAL_DATA,
    HISTORICAL_ROWS_EXCLUDED_FROM_WALLET,
    NO_WALLET_INCOME_EXCLUDED_FROM_SPENDABLE
}
