package com.moneyflowbackend.activity.domain;

public enum ActivityAction {
    TRANSACTION_CREATED,
    TRANSACTION_UPDATED,
    TRANSACTION_VOIDED,
    TRANSACTION_RESTORED,
    TRANSFER_CREATED,
    ADJUSTMENT_CREATED,
    DAILY_CLOSING_COMPLETED,
    WALLET_SNAPSHOT_RECORDED,
    OBLIGATION_CONFIRMED
}
