package com.moneyflowbackend.voice.dto;

public enum VoiceReviewDraftType {
    EXPENSE,
    INCOME,
    INCOME_FACT,
    TRANSFER,
    WALLET_SNAPSHOT,
    DEBT,
    LOAN_DISBURSEMENT,
    LOAN_COLLECTION,
    BORROWING_RECEIPT,
    BORROWING_REPAYMENT,
    SAVINGS,
    SAVINGS_ALLOCATION,
    SINKING_FUND_CONTRIBUTION,
    EMERGENCY_FUND_CONTRIBUTION,
    UNKNOWN
}
